### ISSUE TITLE
文本溢出省略号小技巧

### ISSUE THREAD

**Issue by julytian** [julytian/H5skills#1]
### 单行文字超出省略号
```css
.text{
    width:  100px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-scaple: nowrap;
}
```
### 多行文字超出省略号
```css
.text{
    width: 100px;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 3;   /* 超过3行就显示省略号 */
    text-overflow: ellipsis;
    overflow: hidden;
}
```
