### ISSUE TITLE
使用 :not() 简化样式

### ISSUE THREAD

**Issue by julytian** [julytian/H5skills#2]
[MDN用法](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:not)

一般我们写一个导航条，每个导航之间都设置空隙（除了最后一个），代码以下：
```html
<div class="navbar">
    <a href="#">首页</a>
    <a href="#">关于我们</a>
    <a href="#">个人中心</a>
    <a href="#">联系我们</a>
</div>
```

```css
.navbar a {
    margin-right: 10px;
}
.navbar  a:last-child {
    margin-right: 0;
}
```
看起来总觉得很别扭，现在可以使用 :not() 来简化样式
```css
.navbar a:not(:last-child) {    /* 除了最后一个 */
    margin-right:  20px;
}
```
