### ISSUE TITLE
解决 Android 浏览器下 line-height 垂直居中偏离问题 

### ISSUE THREAD

**Issue by julytian** [julytian/H5skills#3]
结合行高、对齐的关系，结合伪元素得出的黑科技，亲测效果很理想。
```css
.btn::before {
    content: '';
    display: inline-block;
    vertical-align: middle;
    width: 0;
    height: 100%;
    margin-top: 1px;
}
```
